#!/usr/bin/env bash


echo "#=============================="
echo ""
echo "# Freshen up directory structure"
echo "cd ~/data"
echo "rm -rf dotfiles"
echo "mkdir dotfiles"
echo "cd dotfiles"
echo ""

echo "# Dump file contents"
declare -a files=(".bashrc_personal" ".bash_aliases" ".bash_env" ".bash_prompt" ".vimrc" ".unpack")
for i in "${files[@]}"
do
    echo "# ${i}"
    echo "echo "$(cat ${i} | base64)" | base64 -d >> ${i}"
    echo "echo "$(cat ~/.atl_bashrc | base64)" | base64 -d >> .atl_bashrc"
    echo "echo "$(cat ~/dotfiles/qol/minimalwakelock.html | base64)" | base64 -d >> minimalwakelock.html"
    echo "chmod +x ${i}"
    echo "chmod +x .atl_bashrc"
    echo ""
done

echo "# Setup file installation"

# delete historical
echo "cd ~/data"
echo "rm -rf setup.sh"

echo "cd ~/data/dotfiles" # so we can . ./da <tab etc.>
echo "echo \"#!/usr/bin/env bash\" >> setup.sh"
echo "echo \"cd ~/data/dotfiles; ./.unpack; cd ~; source ~/.bashrc_personal; exec \${SHELL} -l\" >> setup.sh"
echo "chmod +x setup.sh"

echo ""
echo "# Invoke setup script!"
echo "cd ~"
echo "source ~/data/dotfiles/setup.sh"
echo "# good to go!"
