colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xe6edfd'

  # Normal colors
  normal:
    black:   '0x15191e'
    red:     '0xbe5046'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xa9b5d8'

  # Bright colors
  bright:
    black:   '0x4c4c4c'
    red:     '0xe06c75'
    green:   '0xa9cc87'
    yellow:  '0xe5c07b'
    blue:    '0x7cb9f9'
    magenta: '0xce88ed'
    cyan:    '0x81d1df'
    white:   '0xffffff'
