# Colors (AtomOneDarkCustomized)

[colors.bright]
black = '#4c4c4c'
blue = '#6ebbff'
cyan = '#6fd4e2'
green = '#a1cd81'
magenta = '#de85f5'
red = '#fa6774'
white = '#ffffff'
yellow = '#edbe73'

[colors.cursor]
cursor = '#ffffff'
text = '#000000'

[colors.normal]
black = '#14191e'
blue = '#4fb2f7'
cyan = '#40bac5'
green = '#8ec573'
magenta = '#d875e5'
red = '#d74b43'
white = '#a7b6dc'
yellow = '#dd9860'

[colors.primary]
background = '#272c35'
foreground = '#e4eeff'

[colors.selection]
background = '#9ba5be'
text = '#000000'
