[colors]
background = '#272c35'
foreground = '#e4eeff'
selection-background = '#9ba5be'
selection-foreground = '#000000'
cursor = '#ffffff'
black = '#14191e'
red = '#d74b43'
green = '#8ec573'
yellow = '#dd9860'
blue = '#4fb2f7'
magenta = '#d875e5'
cyan = '#40bac5'
white = '#a7b6dc'
light_black = '#4c4c4c'
light_red = '#fa6774'
light_green = '#a1cd81'
light_yellow = '#edbe73'
light_blue = '#6ebbff'
light_magenta = '#de85f5'
light_cyan = '#6fd4e2'
light_white = '#ffffff'
