tags = ["dark"]

[theme.colors]
background = "#272c35"
foreground = "#e4eeff"
bright-foreground = "#ffffff"

[theme.colors.palette]
0 = "#14191e"
1 = "#d74b43"
2 = "#8ec573"
3 = "#dd9860"
4 = "#4fb2f7"
5 = "#d875e5"
6 = "#40bac5"
7 = "#a7b6dc"
8 = "#4c4c4c"
9 = "#fa6774"
10 = "#a1cd81"
11 = "#edbe73"
12 = "#6ebbff"
13 = "#de85f5"
14 = "#6fd4e2"
15 = "#ffffff"
